export interface Isapequipment {
    id                 : number;
    id_company?        : string;
    consecutivo?       : number;
    id_psv?            : number;
    cp?                : string;
    tp?                : string;
    plataforma?        : string;
    location?          : string;
    id_cp?             : number;
    id_platform?       : number;
    id_location?       : number;
    sapnumber          : string;
    tag?               : string;
    cont?              : string;
    tagcontainer?      : string;
    protectequipment   : string;
    tagrecipient?      : string;
    statesqprecipient? : string;
    numsaprecipient?   : string;
    unitpress?         : string;
    pressoperatioin?   : string;
    unittemperature?   : string;
    tempoperation?     : number;
    unitplan?          : string;
    maintenanceplam?   : string;
    pressdti?          : number;
    unidaddti?         : string;
    numberdti?         : string;
    coldpress?         : number;
    unitcold?          : string;
    placedownload?     : string;
    backpressure?      : number;
    unitpressure?      : string;
    classification?    : string;
    class?             : number;
    fluent?            : string;
    picture?           :string
  }
