// Generated by https://quicktype.io
export interface Iusers {
  active       : number;
  age          : number;
  country      : string;
  displayName  : string;
  emailu       : string;
  iduser       : number;
  method       : string;
  password     : string;
  phone        : string;
  picture      : string;
  position     : string;
  organization : string;
}



