// Generated by https://quicktype.io
export interface Iusers {
  active:       number;
  age:          number;
  country:      string;
  displayName:  string;
  email:        string;
  iduser:       number;
  method:       string;
  phone:        string;
  picture:      string;
  position:     string;
  organization: string;
}



